spring:
  application:
    name: ASE-Notification-Service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  error:
    include-message: always
  servlet:
    context-path: /api/v1
app:
  repository:
    initialize-with-dummy-data: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
management:
  endpoints:
    web:
      exposure:
        include: health,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins:
    - http://localhost:5173
    - https://sau-portal.de
