spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres.db:5432/appdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    token:
      client-id: ${SECURITY_TOKEN_CLIENT_ID}
      client-secret: ${SECURITY_TOKEN_CLIENT_SECRET}
server:
  servlet:
    context-path: /notification-service/api/v1

user-service:
  url: https://sau-portal.de/team-11-api
  groups-enabled: true
  timeout-ms: 2000

app:
  repository:
    initialize-with-dummy-data: false
